import { SupabaseClient, Session, type User } from "@supabase/supabase-js";
// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
// and what to do when importing types

declare global {
  namespace App {
    interface Locals {
      supabase: SupabaseClient;
      getSession(): Promise<Session | null>;
    }
    interface PageData {
      session: Session | null;
      user: User | undefined;
      profile: unknown; // TODO replace this Profile type from Supabase autogenerated ones
    }
    // interface Error {}
    // interface Platform {}
  }
}

export {};
